---
name: VItemsAPI
main: venndev\plugin\VItemsAPI
version: 1.0
api: [5.0.0]
author: VennDev
description: One plugin for PocketMine-MP that allows you to create custom items.
load: STARTUP
...